version: "3.4"

networks:
  sreality-demo:

volumes:
  postgres-data:

services:
  postgres:
    networks:
      - sreality-demo
    image: postgres:14.5
    environment:
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"

  adminer:
    networks:
      - sreality-demo
    image: adminer
    ports:
      - "8085:8080"
